version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - 6380:6379
  nginx:
    image: "nginx:alpine"
    restart: unless-stopped
    ports:
      - 8088:80
    healthcheck:
      test: [ "CMD", "curl", "-s", "localhost:80" ]
      timeout: 10s
      interval: 2s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.local`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=default"
      - "traefik.http.services.nginx.loadbalancer.server.scheme=http"
      - "traefik.http.services.nginx.loadbalancer.server.port=8088"
